{% set name = "qcelemental" %}
{% set version = "0.27.1" %}
{% set sha256 = "76571f21428083ac9ce12dd15d5275b0a336f44d59bc763cda48f1d4233cff4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry-core >=1.2.0
  run:
    - numpy >=1.12.0
    - pint >=0.10.0
    - pydantic >=1.8.2
    - python >=3.6.0

test:
  imports:
    - qcelemental
  requires:
    - networkx >=2.4.0
    - nglview
    - pytest >=4.0.0
    - scipy
  commands:
    - pytest --pyargs qcelemental -k "not pubchem_multiout_g"

about:
  home: https://github.com/MolSSI/QCElemental
  dev_url: https://github.com/MolSSI/QCElemental
  doc_url: https://molssi.github.io/QCElemental/
  doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
  recipe-maintainers:
    - loriab
    - dgasmith
    - lnaden
    - bennybp
