{% set name = "qcelemental" %}
{% set version = "0.19.0" %}
{% set sha256 = "85f97993bfe5e10db0b4f2c7fe4fefc3248c6cf3bf7e2c65c40999f023e45dd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy >=1.12.0
    - pint >=0.10.0
    - pydantic >=1.5.0,!=1.6.0,!=1.8.0
    - python >=3.6.0

test:
  imports:
    - qcelemental
  requires:
    - networkx >=2.4.0
    - nglview
    - pytest >=4.0.0
    - scipy
  commands:
    - pytest --pyargs qcelemental

about:
  home: https://github.com/MolSSI/QCElemental
  dev_url: https://github.com/MolSSI/QCElemental
  doc_url: https://qcelemental.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
  recipe-maintainers:
    - loriab
    - dgasmith
    - lnaden
    - bennybp
