{% set name = "qcelemental" %}
{% set version = "0.30.0" %}
{% set sha256 = "9c85b7f1178a804d45034af9e5338eb003a5bed015ddf2107b14eccaac78af88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.2.0
    - packaging
  run:
    - numpy
    - pint
    - pydantic >=1.8.2
    - python >={{ python_min }},<3.14.0

test:
  imports:
    - qcelemental
  requires:
    - networkx >=2.4.0
    - nglview
      # networkx and nglview might be imposing a pyqt dependence on qcel for the c-f migrators
    - pytest
    - scipy
    - python {{ python_min }}
  commands:
    - pytest --pyargs qcelemental -k "not pubchem_multiout_g"

about:
  home: https://github.com/MolSSI/QCElemental
  dev_url: https://github.com/MolSSI/QCElemental
  doc_url: https://molssi.github.io/QCElemental/
  doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
  recipe-maintainers:
    - loriab
    - dgasmith
    - lnaden
    - bennybp
