travis:
  secure:
    BINSTAR_TOKEN: oWYCo4UPKnFpnJKCOZB7jcp/LRqIn78aTe7FYsJBa3/t1Z8yhf/K2wTnAG4gD9cByonV9PoWLnYKwyRmvPxhLx7vht9pznYVh+XD3UYZ1YSbCbW9lU/uRb8d0K1O6Tbw8/MHxMgUOOFpIjijFGF8Un9xXGQsO3iZGC5Lj7Q+d4ovc2dr9YCpkOam6MxU15nqgqYTQFAfmWTboNSj13ei3XD3j5dlw8nCSFC37EmK32H9rXwy639ThBtI1sBijT/bZu/JDW9mMX0eKFAcZAxI0vndB9/WRvjN1p85fyELTkzCl3G+btYpt9+QJgrxDPRAvmRbJxUm26VOq3shazf+UAkkgIOT2jA0vqCwdWljUu0w0ZIyFUIw7npq5dqg7Je3iVZukRPd3CHn4nYr+4nAJWetgHz1OpIC83a0d6yPRta5914poWfrn2hToujoERhxhsaYTrlr4PEFjCz+iPRhV+QY5bIBq+pyE7JRpcSx7Wb7SXWOGFW4AC3dQJ7L6rNgKoMDsHUmhJwUIF7ti1MPLg1LDWhgSzDVWNuSMtm9tP3CIFRSByKCxALUc7SJfCSa+WBlizORDSFkl7d4FjjcR0INns3+YvcaagDdtYSQostJjQ/blBT72AvTmum9mSFbrXqOXhITVOkelA6LY9kKlsnyWpkdnoAjf7ybttd+WSI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
